a few more changes to the mkmf template and compile script, but still getting ** undefined reference to `nf_sync_`**, and about a hundred other undefined references,  errors. feel like i am using ALL of the /include and /lib directories; tring to use nc-config, pkg-config tools to accomplish this...